config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts do
    member do
      post '/create_comment' => 'posts#create_comment', as: 'create_comment_to'
      post '/like_post' => 'posts#like_post', as: 'like_to'
    end
    collection do
      delete '/:comment_id/destroy_comment' => 'posts#destroy_comment', as: 'destroy_comment_to'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create_comment, :like_post]
  before_action :is_login?, only: [:create_comment, :like_post, :destroy_comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = true
    if user_signed_in?
      @like = current_user.likes.find_by(post_id: @post.id).nil?
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    (comment_params)
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_comment
    @c = @post.comments.create(comment_params)
  end

  def destroy_comment
    p params[:comment_id]
    @comment = Comment.find(params[:comment_id])
    if @comment.destroy
      respond_to do |format|
        format.js {render 'destroy_comment.js.erb'}
      end
    end
  end

  def like_post
    if Like.where(user_id:current_user.id, post_id: @post.id).first.nil?
      @result = current_user.likes.create(post_id: @post.id)
      p "좋아용"
    else
      @result = current_user.likes.find_by(post_id: @post.id).destroy
      p "좋아용 취소!!"
    end
    @result = @result.frozen? # destroy 후에 memory에는 있고 db에는 없는 상태
  end

  private

    def is_login?
      unless user_signed_in?
        respond_to do |format|
          format.js {render 'please_login.js.erb'}
        end
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents)
    end

    def comment_params # to prevent slq injection
      params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxPractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
    <h1>
      <% if user_signed_in? %>
        <%= link_to "Sign_Out", destroy_user_session_path, method: 'delete', data: {confirm: "로그아웃 하시겠습니까?"}, class:"btn btn-danger" %>
      <% else%>
        <%= link_to "Sign_In", new_user_session_path, class:"btn btn-danger" %>
      <% end %>
      <%= link_to "HOME", root_path, class:"btn btn-info"%>
    </h1>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_item.html.erb
<tr id="comment-<%=comment.id%>">
  <td>
    <%=comment.body%>
  </td>
  <td>
    <%= link_to "삭제", destroy_comment_to_posts_path(comment),
                method: :delete,
                remote: true,
                data: {confirm: "정말로 삭제하시겠습니까?"} %>
  </td>
</tr>

app/views/posts/create_comment.js.erb
alert("댓글 등록 완료!!");
// ajax에서 했기 대문에 js 파일을 먼저 찾는다!! 그래서!! create_comment.js.erb를 먼저 찾은거지!!

$('#comment_body').val("");
var html = "<%= escape_javascript(render(partial: 'posts/item', locals: {comment: @c})) %>";
$('#comment_table tbody').append(html);

app/views/posts/destroy_comment.js.erb
$(function(){
  $("#comment-<%= @comment.id %>").remove();
})(jQuery)

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.contents %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/like_post.js.erb
$('#like_count').text(<%=@post.likes.count%>);
if(<%=@result%>){
  $('#like_button').text("Like").addClass("btn-info").removeClass("btn-danger");
}else{
  $('#like_button').text("Dislike").addClass("btn-danger").removeCLass("btn-info");
}

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/please_login.js.erb
if(confirm("로그인이 필요합니다. \n 로그인 페이지로 이동하시 겠습니까?")){
  location.href = "<%= new_user_session_path %>";  
}

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @post.contents %>
</p>

<%= form_tag create_comment_to_post_path, id: "create_comment" do %>
  <%= text_field_tag "comment[body]"%>
  <%= submit_tag "댓글달기", id: "submit_btn"%>
<% end %>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
<%= link_to 'Back', posts_path, class: "btn btn-danger" %>
<% if @like %>
  <%= link_to "Like".html_safe, like_to_post_path, class: "btn btn-info", id: "like_button"%>
<% else %>
  <%= link_to "Dislike".html_safe, like_to_post_path, class: "btn btn-danger", id: "like_button"%>
<% end %>
<span id='like_count'><%=@post.likes.count%></span>

<table class="table" id="comment_table">
  <thead>
    <tr>
      <th width="80%">댓글</th>
      <th width="20%">삭제</th>
    </tr>
  </thead>
  <tbody>
    <%@post.comments.each do |p|%>
      <!-- <tr>
        <td><%= p.body%></td>
        <td>
        <%#= link_to "삭제", destroy_comment_to_posts_path(p),
                      method: :delete,
                      remote: true,
                      data: {confirm: "정말로 삭제하시겠습니까?"} %>

        </td>
      </tr> -->
      <%= render partial: 'posts/item', locals: {comment: p } %>
    <%end%>
  </tbody>
</table>

<script>
  $(document).ready(function(){
    // like
    $('#like_button').on('click', function(e){
      e.preventDefault();
      alert("like button clicked")
      $.ajax({
        method: "POST",
        url: "<%= like_to_post_path %>"
      })
    })
    // comments
    var form_var = $('#create_comment')
    form_var.on('submit', function(event){
      event.preventDefault(); // prevent default form action!!
      // var reply = $('#body').val();
      var reply = form_var.serialize(); // 모든 input 정보를 parameter로 바꿔주는 것!!
      console.log(reply);
      $.ajax({
        url:  "<%= create_comment_to_post_path %>",
        method: "POST",
        data: reply
        // data: {body: reply}
      })
    });
  });
</script>